### ISSUE TITLE
Filemaker Links in Readme and on the "How to Page" are no longer active

### ISSUE THREAD

**Issue by toddebner** [soliantconsulting/FileMakerID_token#5]
Complex Process Link on "Your Guide to Using the Data API...." is broken:
   https://fmhelp.filemaker.com/cloud2/edition/en/customer-console-help/#page/fcc-help%2Fcreate-fmid-token.html

Links on the readme are invalid
(See the documentation at https://your_FMC_server.account.filemaker-cloud.com/fmi/data/apidoc/#operation/login)

The help describes how to go about obtaining a token based on your FileMaker ID: https://fmhelp.filemaker.com/cloud2/edition/en/customer-console-help/#page/fcc-help%2Fcreate-fmid-token.html 

Are there new / valid links for these references?

**Comment by wimdecorte** [comment]
I've updated the link to the FM Cloud page that describes fmid.
But that first link is a dummy to indicate where on your own FM Cloud instance you can find the API documentation itself.  I've updated it to make it a little more clear that you need to specify your own instance.
